# SPDX-FileCopyrightText: 2020 tqtezos
# SPDX-License-Identifier: MIT

<<: !include "./hpack/module.yaml"

name:                stablecoin
version:             0.1.0.0

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            FA2-based tezos stablecoin smart contract
category:            Blockchain

description:         Please see the README on GitHub at <https://github.com/tqtezos/stablecoin#readme>

verbatim:
  cabal-version: 2.2

library:
  <<: *lib-common

  default-extensions:
    - RebindableSyntax
    - DerivingStrategies
    - DeriveAnyClass

  dependencies:
    - morley-prelude
    - lorentz
    - morley
    - indigo
    - morley-ledgers
    - tasty-quickcheck
    - fmt

executables:
  stablecoin:
    <<: *exec-common

    dependencies:
      - morley-prelude

tests:
  stablecoin-test:
    <<: *test-common

    default-extensions:
      - DerivingStrategies
      - DeriveAnyClass

    dependencies:
      - HUnit
      - hspec
      - containers
      - morley-prelude
      - morley
      - morley-ledgers-test
      - lorentz
      - filepath
      - tasty
      - tasty-hunit-compat
      - tasty-hspec
      - text
      - stablecoin
