# SPDX-FileCopyrightText: 2020 tqtezos
# SPDX-License-Identifier: MIT
# TODO: rewrite it to haskell.nix

env:
  NIX_PATH: nixpkgs=https://github.com/nixos/nixpkgs/archive/b640dbd00877f51616750e347a32fbcb49d2968c.tar.gz

steps:
 - command: nix run nixpkgs.reuse -c reuse lint
   label: reuse lint
 - command: .buildkite/check-trailing-whitespace.sh
   label: check trailing whitespace
 - command: "nix run -f https://github.com/serokell/xrefcheck/archive/b54c38d91bd45e5c402ebf51d68c653faf959c2c.tar.gz -c xrefcheck"
   label: xrefcheck
   soft_fail: true
 - label: build library
   command: nix build -L -f. lib
 - label: test
   commands:
     - nix build -L -f. test
     - cd result
     - ./bin/stablecoin-test
 - label: check LIGO contract
   command: nix build -L -f. tezos-contract
